### ISSUE TITLE
Mechanized Assault & eXploration Reloaded

### ISSUE THREAD

**Issue by neuromancer** [klei1984/max#4]
In case you are not aware of it, there is a reimplementation of this game called [Mechanized Assault & eXploration Reloaded](https://www.maxr.org/). Perhaps it could be useful for this port?

**Comment by klei1984** [comment]
- I worked on that like 8 or 10 years ago for a short period. MAX:R is all about network play. It has a good community and is still actively developed. Beko created a very nice architecture which I, even 10 years later, would not be able to come any close to. Single player, as far as I know, is not planned though. MAX:R is basically the EU or German community hub.
- There was also a Russian community hub via RU Max Club or MAX:G or MAX Gold which took another approach and had several projects and created several tools. I also worked with Artlav for a short time there.
- Then there is MAX:T or MAX Touch which targets mobiles and has an interesting game mode that works like post mail based chess if I am not mistaken. The authors of MAX:T have awesome designers and graphic artists. I assume some of them do game development for a living.
- Then MAX:R had a predecessor written in Delphi by a single person if I remember correctly.
- Then there is or was FreeMAX which is abandoned.
- Then there is another MAX port on github from [mikhail-khalizev](https://github.com/mikhail-khalizev/max) which is probably far more superior already to my own attempt.

Most of these remakes, ports, recreations differ in their visions, licenses, feature sets, etc. and I look into their implementations from time to time to learn SDL or other aspects of game design or toolchain. Actually my github toolchain and build environment is fully based on Jagged Alliance 2: stracciatella which is another amazing project on github.

There is a very good French [fan page](http://godrage.online.fr/MAX/) which sums up most of the active MAX projects.
