### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by mape83** [klei1984/max#5]
The current link to the binaries https://github.com/klei1984/max/blob/master/x is somewhat dead :-).

**Comment by klei1984** [comment]
The reason for this is that releases do not have binaries yet. It is not intended for users to download latest master builds and play test them as it would lead to misleading and unnecessary defect reports.

Releases do not have installers attached to the release baselines yet, as I could not figure out how to auto detect dependent shared libraries and attach them to the installers via CMAKE and CPACK as well as one additional risk that needs to be solved before self contained installers would be created with shared libraries is to make sure that the licenses of such shared libraries are compatible with the project and all necessary documentation is bundled as required.

All these tasks will eventually be done at one point or another. Maybe for v0.3.0 (networking) or v0.4.0 (audio and MVE video playback).

**Comment by mape83** [comment]
Thanks for the reply. 

I was just happy to see someone tries to improve the current M.A.X. experience.  

I wish you success with your project and hope that your motivation will never let you down. 

Best

**Comment by klei1984** [comment]
Thanks :blush:

**Comment by klei1984** [comment]
Added link to releases page (binaries are not yet available there though)
